trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:

- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install --legacy-peer-deps --unsafe-perm=true --no-audit
    npm run build
  displayName: 'npm install and build'

- script: |
    echo "This is a placeholder step; no changes are made."
  displayName: 'No-op step'

# Snyk Security Scan for Application Dependencies
- task: SnykSecurityScan@1
  inputs:
    serviceConnectionEndpoint: 'snykoattacko'
    testType: 'app'
    targetFile: 'package.json'
    monitorWhen: 'always'
    failOnIssues: false
    projectName: 'calculator-project/CRM Frontend'
    organization: 'f6ff1f1e-b60e-43aa-91ab-fad13fbc3519'
    reportFormat: 'html'
    reportFile: '$(Build.ArtifactStagingDirectory)/snyk-app-report.html'
  displayName: 'Run Snyk App Scan'

- task: SonarCloudPrepare@3
  inputs:
    SonarCloud: 'sonar-connection'
    organization: 'demodevopsyl'
    scannerMode: 'cli'
    cliScannerVersion: '6.2.1.4610'
    configMode: 'manual'
    cliProjectKey: 'davidputra2812_CRM-Frontend'
    cliProjectName: 'CRM Frontend'
    cliSources: '.'

- task: SonarCloudAnalyze@3

- task: SonarCloudPublish@3
  inputs:
    pollingTimeoutSec: '300'